session:
  name: sid
  secret: 123
  domain: "localtest.me"
  loginUrl: http://auth.localtest.me/login

users:
  - username: test
    # plain password: test
    password: $2a$12$3omo8yfJJotGka4PkUWjw.FD5juAS.G9XKWK1ywXb6Oe7CnXd5rgi
